version: 2.1

orbs:
  hdwallet:
    executors:
      node:
        docker:
          - image: circleci/node:10.16.3
          - image: kktech/kkemu:v6.2.0-hotfix.0
    jobs:
      dependencies:
        description: Get deps and persist to workspace
        executor: node
        steps:
          - run: sudo apt-get install libudev-dev libusb-dev libusb-1.0
          - checkout
          - run:
              name: Authenticate with registry
              command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
          - restore_cache:
              name: Restore Yarn Package Cache
              keys:
                - cache-v4-{{ checksum "yarn.lock" }}
          - run: yarn --frozen-lockfile --cache-folder ./.yarn-cache
          - persist_to_workspace:
              root: .
              paths:
                - node_modules
                - .npmrc
                - .yarn-cache
          - save_cache:
              name: Save Yarn Package Cache
              key: cache-v4-{{ checksum "yarn.lock" }}
              paths:
                - .yarn-cache
          - run:
              name: Ensure repo is clean from uncommitted changes, likely yarn.lock is out of date
              command: git diff --quiet || exit 1
      build:
        description: Build all modules
        executor: node
        steps:
          - checkout
          - attach_workspace:
              at: .
          - restore_cache:
              keys:
                - cache-v4-{{ checksum "yarn.lock" }}
          - run: yarn --cache-folder .yarn-cache
          - run:
              no_output_timeout: 30m
              name: Build packages
              command: yarn build
          - persist_to_workspace:
              root: .
              paths:
                - packages/*/dist
          - save_cache:
              key: cache-v4-{{ checksum "yarn.lock" }}
              paths:
                - "packages/hdwallet-core/.rts2_cache_cjs"
                - "packages/hdwallet-core/.rts2_cache_es"
                - "packages/hdwallet-core/.rts2_cache_umd"
                - "packages/hdwallet-keepkey/.rts2_cache_cjs"
                - "packages/hdwallet-keepkey/.rts2_cache_es"
                - "packages/hdwallet-keepkey/.rts2_cache_umd"
                - "packages/hdwallet-trezor/.rts2_cache_cjs"
                - "packages/hdwallet-trezor/.rts2_cache_es"
                - "packages/hdwallet-trezor/.rts2_cache_umd"
                - "packages/hdwallet-keepkey-chromeusb/.rts2_cache_cjs"
                - "packages/hdwallet-keepkey-chromeusb/.rts2_cache_es"
                - "packages/hdwallet-keepkey-chromeusb/.rts2_cache_umd"
                - "packages/hdwallet-keepkey-nodehid/.rts2_cache_cjs"
                - "packages/hdwallet-keepkey-nodehid/.rts2_cache_es"
                - "packages/hdwallet-keepkey-nodehid/.rts2_cache_umd"
                - "packages/hdwallet-keepkey-webusb/.rts2_cache_cjs"
                - "packages/hdwallet-keepkey-webusb/.rts2_cache_es"
                - "packages/hdwallet-keepkey-webusb/.rts2_cache_umd"
      test:
        description: Run tests
        executor: node
        environment:
          JEST_JUNIT_OUTPUT: "test-results/js-test-results.xml"
        steps:
          - checkout
          - attach_workspace:
              at: .
          - restore_cache:
              keys:
                - cache-v4-{{ checksum "yarn.lock" }}
          - run: yarn --cache-folder .yarn-cache
          - run:
              name: Run tests
              command: yarn run test:ci
          - store_test_results:
              path: test-results
      release-packages:
        description: Build and release local dependency packages
        executor: node
        steps:
          - checkout
          - attach_workspace:
              at: .
          - run: yarn --cache-folder .yarn-cache
          - run: git status
          - run: ./node_modules/.bin/lerna publish from-package --yes
workflows:
  version: 2
  Build and Release:
    jobs:
      - hdwallet/dependencies:
          name: dependencies
      - hdwallet/build:
          name: build
          requires:
            - dependencies
      - hdwallet/test:
          name: test
          requires:
            - dependencies
            - build
      - hdwallet/release-packages:
          name: release-packages
          requires:
            - test
            - build
          filters:
            branches:
              only:
                - master

